version: "3"
services:
  image_app:
    build:
      context: .
      dockerfile: dockerfile.app
    ports:
      - 3000:3000
    restart: always

    depends_on:
      - image_bdd
    
    volumes:
      - app-data:/app/data

  image_interface:
    build:
      context: .
      dockerfile: dockerfile.interface
    ports:
      - 80:80

  image_bdd:
    build:
      context: .
      dockerfile: dockerfile.bdd
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: "!Sa122001mi"

    ports:
      - 5432:5432

    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  app-data:
  db-data:
